import React from "react"
import LocalSelectableCard from "./LocalSelectableCard"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  LocalSelectableCard,
  "https://www.figma.com/design/hpGEtO60qoTAgCRWjRH3Mc/Demo-Day?node-id=2026-4080&m=dev",
  {
    props: {
      title41616: figma.string("✏️ title"),
      sectornumber4162: figma.string("✏️ sector number"),
      checkbox1510: figma.boolean("checkbox"),
      expanded: figma.boolean("expanded"),
      type: figma.enum("type", {
        top: "top",
        bottom: "bottom",
      }),
      state: figma.enum("state", {
        idle: "idle",
        "selected-hover": "selected-hover",
        selected: "selected",
        active: "active",
        hover: "hover",
        loading: "loading",
      }),
    },
    example: (props) => (
      <LocalSelectableCard
        title={props.title41616}
        section={props.sectornumber4162}
        checkbox={props.checkbox1510}
        expanded={props.expanded}
      />
    ),
  },
)

